services:
  - type: web
    name: excel-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        value: <REPLACE_WITH_YOUR_API_KEY>

  - type: web
    name: excel-frontend
    env: python
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py --server.port 10000
    plan: free
